---
name: DhMakePerl
version: 0.67
author: []
abstract: create Debian source package from CPAN dist
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
build_requires:
  File::Touch: 0
  Test::Deep: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
requires:
  AptPkg::Cache: 0
  AptPkg::Config: 0
  Array::Unique: 0
  CPAN: 0
  Carp: 0
  Cwd: 0
  Dpkg: 0
  Dpkg::Source::Package: 0
  Email::Date::Format: 0
  File::Basename: 0
  File::Copy: 0
  File::Find::Rule: 0
  File::Spec: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  IO::File: 0
  IO::Uncompress::Gunzip: 0
  List::MoreUtils: 0
  Module::Build: 0
  Module::CoreList: 0
  Module::Depends: 0
  Module::Depends::Intrusive: 0
  Parse::DebControl: 0
  Parse::DebianChangelog: 0
  Storable: 0
  Text::Diff: 0
  Text::Wrap: 0
  Tie::File: 0
  Tie::IxHash: 0
  User::pwent: 0
  WWW::Mechanize: 0
  YAML: 0
  perl: 5.010
  version: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Debian::AptContents:
    file: lib/Debian/AptContents.pm
  Debian::Control:
    file: lib/Debian/Control.pm
  Debian::Control::FromCPAN:
    file: lib/Debian/Control/FromCPAN.pm
  Debian::Control::Stanza:
    file: lib/Debian/Control/Stanza.pm
  Debian::Control::Stanza::Binary:
    file: lib/Debian/Control/Stanza/Binary.pm
  Debian::Control::Stanza::CommaSeparated:
    file: lib/Debian/Control/Stanza/CommaSeparated.pm
  Debian::Control::Stanza::Source:
    file: lib/Debian/Control/Stanza/Source.pm
  Debian::Dependencies:
    file: lib/Debian/Dependencies.pm
  Debian::Dependency:
    file: lib/Debian/Dependency.pm
  Debian::DpkgLists:
    file: lib/Debian/DpkgLists.pm
  Debian::Rules:
    file: lib/Debian/Rules.pm
  Debian::WNPP::Bug:
    file: lib/Debian/WNPP/Bug.pm
  Debian::WNPP::Query:
    file: lib/Debian/WNPP/Query.pm
  DhMakePerl:
    file: lib/DhMakePerl.pm
    version: 0.67
  DhMakePerl::Command::Packaging:
    file: lib/DhMakePerl/Command/Packaging.pm
  DhMakePerl::Command::dump_config:
    file: lib/DhMakePerl/Command/dump_config.pm
  DhMakePerl::Command::help:
    file: lib/DhMakePerl/Command/help.pm
  DhMakePerl::Command::locate:
    file: lib/DhMakePerl/Command/locate.pm
  DhMakePerl::Command::make:
    file: lib/DhMakePerl/Command/make.pm
    version: 0.65
  DhMakePerl::Command::refresh:
    file: lib/DhMakePerl/Command/refresh.pm
  DhMakePerl::Command::refresh_cache:
    file: lib/DhMakePerl/Command/refresh_cache.pm
  DhMakePerl::Config:
    file: lib/DhMakePerl/Config.pm
  DhMakePerl::PodParser:
    file: lib/DhMakePerl/PodParser.pm
  DhMakePerl::Utils:
    file: lib/DhMakePerl/Utils.pm
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
